### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by AntonOks** [raku-community-modules/Testo#24]
WARNING: Version mismatch for Testo ("https://github.com/raku-community-modules/perl6-Testo.git") found. META6.json has "1.003007" but latest 'git tag' is "1.002001"

**Comment by 2colours** [comment]
@AntonOks added a tag 1.003007 for the latest commit, for the time being

Eventually, this repo should be migrated to the "zef ecosystem", it's just I wanted to estimate the impact beforehand.
